# Uncomment the next line to define a global platform for your project
platform :ios, '10.2'

target 'PushyMyNotifications' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PushyMyNotifications

  target 'PushyMyNotificationsTests' do
    inherit! :search_paths
    pod 'Firebase/Core'
    pod 'Firebase/Messaging'
  end

end
